### PR TITLE
Add Al electron diffraction powder

### PR DESCRIPTION
**Pull request by elena-pascal**
Needed for powder_calibrate test

### CODE REVIEW

**Comment by Anthchirp** [comment]
Would you mind if we renamed the file to `aluminium_standard`?
If would also be great to know who took the dataset (unless you did that yourself) and on what visit.

**Comment by dagewa** [comment]
I believe the images were collected by Yun Song, and there is a copy at `/dls/ebic/data/staff-scratch/YunSong/Yun_cameralength_cal/cameralength_cal`. I'm not sure of the original visit

**Comment by Anthchirp** [comment]
probably m12 then?

**Comment by elena-pascal** [comment]
```
(base) [fyi77748@cs03r-sc-serv-36 2020]$ pwd
/dls/m12/data/2020
(base) [fyi77748@cs03r-sc-serv-36 2020]$ ls -lt | grep Jan
drwxrws---+ 13 gda2 cm28024_2   4096 Jan 26  2021 cm28024-2
```
Can I conclude `cm28024-2` is the visit number? I did email Yun and waiting for a reply.

**Comment by elena-pascal** [comment]
Yun said the calibration was done without a visit code. Anything else we can use to identify the data?

**Comment by Anthchirp** [comment]
If you could add DLS, m12, and Yun's name then that will be fine :+1:

**Pull request merged**
